### ISSUE TITLE
Tracking upstream improvements

### ISSUE THREAD

**Issue by daxpedda** [khonsulabs/fabruic#1]
- [ ] PSK support: https://github.com/ctz/rustls/issues/174
- [ ] Drop X.509: https://github.com/ctz/rustls/issues/423
- [ ] Support IP as domain:
  - [ ] WebPKI:
    - [ ] https://github.com/briansmith/webpki/issues/54
    - [ ] https://github.com/briansmith/webpki/issues/130
    - [ ] https://github.com/briansmith/webpki/issues/90
  - [ ]  RusTLS
    - [ ] https://github.com/ctz/rustls/issues/184
    - [ ] https://github.com/ctz/rustls/issues/206
    - [ ] https://github.com/ctz/rustls/issues/331
    - [ ] https://github.com/ctz/rustls/issues/578
  - [ ] QUINN: https://github.com/quinn-rs/quinn/issues/564
- [ ] Server Migration: https://github.com/quinn-rs/quinn/issues/716
- [ ] Async Executor Agnosticism: https://github.com/quinn-rs/quinn/issues/502
- [ ] Certificate Rotation: https://github.com/quinn-rs/quinn/issues/474
- [ ] Async Resolver:
  - [ ] https://github.com/ctz/rustls/issues/89
  - [ ] https://github.com/ctz/rustls/issues/430
  - [ ] https://github.com/ctz/rustls/issues/468

**Comment by daxpedda** [comment]
I did some research on OCSP, this is actually quiet important.
Especially when we go production in CV, we have to be able to protect ourselves against a compromise of our private key.

The only alternative I know, CRLs, isn't available in the Rust community and as far as I know there are no plans to add support.
